### ISSUE TITLE
PHashMap's Seq() implementation may be broken

### ISSUE THREAD

**Issue by kivikakk** [dmiller/go-seq#1]
Hey there,

I'm not sure (i) if go-seq is still maintained, nor (ii) if I'm using `Seq()` the way I ought to be, but if I am, it appears PHashMap's implementation may be broken.  See the following test:

``` go
package runtime

import (
        "fmt"
        "github.com/dmiller/go-seq/seq"
        "testing"
)

func TestMap(t *testing.T) {
        m := seq.NewPHashMapFromItems("a", 1, "b", 2)
        if m.ValAt("a") != 1 {
                t.Errorf("a /= 1")
        }
        if m.ValAt("b") != 2 {
                t.Errorf("b /= 2")
        }

        for s := m.Seq(); s != nil; s = s.Next() {
                fmt.Printf("%v\n", s)
        }
}
```

This crashes as follows on `s.Next()` after the last element:

``` go
&{[a 1 b 2] 0 <nil> {<nil>}}
&{[a 1 b 2] 2 <nil> {<nil>}}
<nil>
--- FAIL: TestMap (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xd3e81]

goroutine 5 [running]:
testing.func·006()
        /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:441 +0x181
github.com/dmiller/go-seq/seq.(*hmnodeSeq).Next(0x0, 0x0, 0x0)
        /Users/kivikakk/Code/go/src/github.com/dmiller/go-seq/seq/phashmap.go:784 +0x31
_/Users/kivikakk/Code/narset/runtime.TestMap(0x20830a000)
        /Users/kivikakk/Code/narset/runtime/go-seq_test.go:17 +0x408
testing.tRunner(0x20830a000, 0x24cf30)
        /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x1cd210, 0x24cf30, 0x1, 0x1, 0x1)
        /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0x2082d21e0, 0x259560)
        /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:485 +0x6c
main.main()
        _/Users/kivikakk/Code/narset/runtime/_test/_testmain.go:52 +0x1d5
exit status 2
FAIL    _/Users/kivikakk/Code/narset/runtime    0.004s
```

Another more straightforward way to test this is to just call `sequtil.SeqEquiv(m.Seq(), m.Seq())`, and note it crashes in `seq.(*hmnodeSeq).First` with nil args as well.

**Comment by dmiller** [comment]
Oh my, I didn't know anyone had ever looked at this code.
I haven't worked on that code for a long time.  Basic functionality is
there, but it needs more testing.
The STM stuff definitely doesn't work, but the sequence stuff mostly should.

I'm about to take some long plane rides.  I'll spend some of the time in
the air looking at the bug you found and developing more tests for the code.

-David
